# -*- coding: utf-8 -*-
# The Undertaker's Kindness — VO-synced shot list builder.
# Pairs authored image prompts with scene_calculator.py timecodes (from the
# narration-only VO, 41:31). One image per scene; its duration IS the narration
# length under it, so placement is drop-at-timecode. Text-free, names inline,
# no em-dashes. Ingredients: Abel | Amos | Price | Adair | Cora | Lila.
import csv

PROMPTS = [
"A fine black lacquered coach drawn by a matched pair rolls into a dusty frontier main street at midday, townsfolk turning to stare",
"Adair — A thin dry spectacled lawyer in a black suit stands at a saloon bar, hat set down, asking a quiet question, rough men listening",
"Adair — An elderly lawyer looks slowly around a hushed saloon, sharp gray eyes reading every face, a man who knows more than he asks",
"Adair — Close-up of a spectacled lawyer speaking one deliberate question, calm and surgical, warm saloon lamplight, tense faces behind him",
"Amos — A frail bent old man in a patched drover coat shuffles into a cold purple-dusk frontier street, sick and shaking, road-worn",
"Amos — A ragged old man shuffles down a boardwalk as well-dressed townsfolk cross the street away from him, cold shoulders, gray light",
"Abel — A big heavy-shouldered undertaker in a rusty black coat stands in a lamplit workshop doorway, plain gentle weathered face, coffins behind him",
"Abel — A big undertaker planes a smooth pine coffin board by lamplight in a sawdust workshop, careful large hands, quiet devotion",
"Abel — An undertaker gently combs the white hair of a peaceful old man lying still with eyes closed on a workbench, tender, lamplight",
"Abel — A big undertaker digs a grave alone on a grassy hilltop in long golden evening light, shovel in hand, a distant creek below",
"Abel — An undertaker stands alone at a fresh graveside on a hill at dusk, hat held over his chest, head bowed, reading words into the wind",
"Abel — A big undertaker counts the last worn coins from a small tin into his palm by lamplight, resolute, a granite slab behind him",
"Abel — An undertaker chisels a granite headstone by oil-lamp light late at night, mallet and chisel in careful hands, absorbed",
"Amos — A frail old man in rags stands in weak light, his eyes holding a hidden depth and a secret weight, road-worn and unreadable",
"Amos — A dying old man in a patched coat walks a lonely frontier road at dusk, bent and failing, wide empty country behind him",
"A leather document case and a folded will with a wax seal on a dark city desk, lamplight, an ink pen beside it, quiet and formal",
"Price — A well-fed man in a fine suit with bright silver vest buttons rises smoothly in a saloon, an oiled civic smile spreading, greedy",
"Abel — A big undertaker digs a pauper's grave alone on a hill in evening light, unaware, humble and steady, a town gathering far below",
"A plain worn brass pocket watch lying closed on a rough workbench in warm lamplight, humble and significant, sawdust around it",
"Abel, Amos — A poor undertaker sets a warm plate before a ragged old man at a lamplit table, quiet dignity given freely, gold light",
"Adair, Price — A lawyer holds up a closed brass pocket watch before a sweating silver-buttoned man in a lamplit saloon, tense, crowd watching",
"Abel — A lonely undertaker eats supper alone over his workbench at night, one lamp, sawdust and coffin pine around him, solitary",
"Abel — Close-up of a big gentle undertaker's weathered face and large careful hands, patient tired brown eyes, lamplight, quiet strength",
"Abel — A black undertaker's wagon rolls slowly down a dusty frontier street as mothers hush children and pull them close, wary faces",
"Abel — A big undertaker in a worn rusty black coat enters a saloon, men falling silent and drifting away from the bar, cold distance",
"Abel — Close-up of a frayed rusty black coat gone brown at the seams on a big man's shoulders, poverty in the detail, gray daylight",
"A lonely plank workshop building with one lit window at the dark end of a frontier street at night, isolated, warm glow",
"Lila — A bright laughing young woman with honey-brown hair and freckles in a cream calico dress and apron, warm golden light, full of joy",
"Lila — A young woman lies pale and still with eyes closed on a bed in dim candlelight, peaceful, a shadow of fever over the room",
"Abel — A big man planes a coffin board alone at midnight by lamplight, shoulders bent with grief, tears falling into the sawdust",
"Abel — A big undertaker stands utterly alone at a graveside on a hill in gray driving rain, hat off, head bowed, wrenching solitude",
"Abel — Close-up of an undertaker's rain-wet grieving face hardening into quiet resolve, a decision being made, gray storm light",
"Abel — An undertaker stands hat-off over a plain grave at dusk reading a verse for a stranger, alone but reverent, long shadows",
"Abel — A big undertaker gently lays clean linen into a simple pine coffin in his lamplit workshop, careful and respectful, warm light",
"Abel — An undertaker counts thin coins from a tin over his workbench by lamplight, worry on his face, an empty purse, hard arithmetic",
"Amos — A frail old man in a patched coat shuffles into a raw purple-dusk frontier street, wind-bitten and failing, one lamp glowing far off",
"Price — A well-fed man in a silver-buttoned vest stands on a fine hotel porch, thumbs in his vest, cold appraising eyes, proprietary",
"Price — A prosperous town boss in a fine charcoal suit and silver buttons surveys a frontier main street he owns, silver-headed cane, smug",
"Price — A well-fed man gestures grandly to a small crowd on a boardwalk, giving a civic speech, self-satisfied, warm daylight",
"Price — Close-up of a smooth confident face with a thin cold smile and calculating eyes, utterly indifferent, silver buttons gleaming",
"Price — A speculator frowns coldly across a street at a distant undertaker's shop, contempt on his face, a ledger under his arm",
"Price — A well-fed man stands on a grassy hilltop at dusk surveying the best view in town, gesturing possessively at the slope, greedy plans",
"Price — A town boss leans over a table addressing seated council men in a lamplit room, persuading, cane tapping, scheming",
"Price — A well-fed man taps his silver-headed cane on a boardwalk delivering a cold line, thin smile, evening light",
"Amos — A small wiry bent old man in a three-patch drover coat stands in a raw wind at purple dusk on a frontier street, shaking, frail",
"Amos — A frail old man climbs three steps toward a fine hotel porch, gripping the rail, road-dust dripping, hopeful and exhausted, dusk",
"Amos — A ragged old man stands humbly on a clean lit hotel porch, hat in weathered hands, asking quietly, small against the grand doorway",
"Amos — Close-up of a frail old man's lined face asking softly, watery pale-blue eyes, dignity in poverty, warm porch lamplight",
"Price, Amos — A well-fed man in silver buttons looks a ragged old man over head to toe with cold appraisal on a hotel porch, judging",
"Price, Amos — A town boss speaks down smoothly to a bent old man on a porch, false sorrowful courtesy, the old man taking it quietly",
"Price — A well-fed man gestures dismissively toward the dark street beyond his hotel porch, sending someone away, cold, lamplight",
"Amos — A frail old man turns and shuffles back down hotel steps into the cold dark street, shoulders bowed, receiving contempt like weather",
"Amos — A ragged old man stands warming his hands at a saloon stove while rough regulars smirk and mutter, unwelcome, warm harsh light",
"Amos — A frail old man is turned away from a barn doorway by a nervous young stable hand, gently refused, lantern light, cold night",
"Amos — A frail old man sits huddled on the steps of the last plank building on a dark street, one warm lit window above him, night",
"Abel, Amos — A big undertaker opens his lamplit door into the dark and finds a frail old man huddled on his steps, surprise and concern",
"Amos — A frail old man looks up from a doorstep with a dry weary smile, no self-pity, warm lamplight on his lined face, night",
"Abel, Amos — A ragged old man on a doorstep gestures wryly toward a coffin-filled lamplit workshop, dark humor, a big man in the doorway",
"Abel — A big undertaker stands aside holding his workshop door open, gesturing a welcome into warm firelight, kind, night behind him",
"Abel, Amos — A big undertaker gently takes a stumbling ragged old man by the arm and helps him over a lamplit threshold, tender care",
"Abel, Amos — A big undertaker sets a bowl of stew before a ragged old man wrapped in a blanket by a warm stove, quiet kindness, gold light",
"Abel, Amos — A big undertaker and a ragged old man sit in easy silence by a glowing stove at night, two lonely men at rest, warm light",
"Amos — A frail old man talks quietly by a stove, firelight on his lined face, a flinty wry look, holding back more than he tells",
"Abel, Amos — A big undertaker almost smiles listening to an old man by the stove, something long asleep waking in his tired face, warm light",
"Abel, Amos — Two weary men sit talking slowly by a low stove at night, undertaker and tramp, shared grief between them, dim gold light",
"Abel — A big undertaker speaks haltingly by the stove, grief and relief on his face, telling a long-held sorrow aloud for the first time",
"Amos — A frail old man listens intently by firelight, saying nothing, deep understanding in his watery eyes, warm quiet night",
"Amos — A frail old man stares into a stove fire, haunted by an old loss, quiet grief on his lined face, dim warm light",
"Amos — Close-up of an old man's face by firelight saying a hard word, a flicker of a former life behind his eyes, weary regret",
"Amos — A frail old man's shaking hands cradle a plain worn brass pocket watch in firelight, his last possession, tender and sad",
"Amos, Abel — A frail old man presses a brass pocket watch into a big undertaker's reluctant hands by the stove, insistent, warm light",
"Amos — Close-up of an old man's earnest lined face pressing a gift, wry and grave, firelight, watery pale-blue eyes fixed and certain",
"Abel — A big undertaker holds a small brass watch and looks at it, moved and uncertain, firelight, an old man's shape beside him",
"Abel — A big undertaker slips a brass pocket watch into his vest pocket by lamplight, solemn, not opening it, quiet respect",
"A small brass pocket watch resting in a worn vest pocket, warm lamplight, a single significant object, shallow focus",
"Abel, Amos — A big undertaker sits close by a cot where a frail old man lies wrapped and failing, holding his hand, one lamp lit, night vigil",
"Abel — A big undertaker keeps a lamp burning by a sickbed, holding a frail hand in the dark, steady tender vigil, warm pool of light",
"Amos — Close-up of a frail old man's peaceful clear face on a pillow looking up with love and gratitude, lamplight, a last lucid moment",
"Amos — A dying old man speaks his last words softly from a pillow, gripping a hand, serene and certain, warm lamplight, eyes shining",
"Abel, Amos — A frail old man's thin hand grips a big careful hand tightly on a blanket, lamplight, a bond in the final moment",
"Amos — A frail old man lies at peace with eyes closed on a cot, a lamp burning low beside him, a big man's bowed head near, still and quiet",
"Price — A well-fed man in silver buttons smirks and taps his cane in a saloon, spreading a cruel joke, men laughing around him",
"Price — A town boss holds forth at a saloon bar with a mocking grin, cane in hand, an ugly amused crowd, warm harsh light",
"Price — Close-up of a smug well-fed face delivering a cruel line, thin cold smile, silver buttons, contemptuous",
"Abel — A big undertaker stands in his workshop choosing clear straight pine boards, resolute and unhurried, ignoring the town, lamplight",
"Abel — A big undertaker planes a fine straight pine board smooth as a church rail in his lamplit workshop, careful devotion, sawdust curling",
"Cora — A calm strong-boned woman with steady grey eyes and auburn hair sews white linen by lamplight, quiet warmth, dark green dress",
"Abel, Cora — A big undertaker speaks humbly to a seamstress across a bolt of white cloth, she meets his eyes kindly, a bond forming, warm light",
"Cora — A seamstress folds a length of clean white linen and presses it into a big man's hands, refusing payment, gentle steady kindness",
"Abel — A big undertaker gently buttons his own good Sunday coat onto a peaceful still old man lying with eyes closed, reverent, lamplight",
"Abel — A big undertaker holds a brass watch over an open pine coffin then draws it back, keeping a promise, solemn, lamplight",
"Abel — A big undertaker digs a grave on the southeast corner of a green hill in long golden evening light, a creek winding below, alone",
"Abel, Price — A well-fed man in silver buttons stands over a grave-hole scolding a big undertaker who digs chest-deep, defiant calm, hilltop dusk",
"Abel — A big undertaker stands chest-deep in a grave leaning on his shovel, speaking plainly up at someone, quiet unshakable dignity, dusk",
"Abel — A big undertaker climbs from a finished grave at dusk, dirt on his hands, resolute, a fresh mound and a hill view behind him",
"Abel — A big undertaker empties the last coins from a small tin into his palm by lamplight, all he has, quiet resolve, workbench",
"A small tin coffee can tipped out on a workbench showing a few worn coins, poverty laid bare, warm lamplight, shallow focus",
"A rough grey granite slab leaning in a dusty stone-mason's yard, unclaimed, hard daylight, tools and stone dust around it",
"Abel — A big undertaker hauls a heavy granite slab onto a wagon on a country road, straining, determined, wide frontier behind him",
"Abel — A big undertaker chisels letters into a granite slab by oil-lamp light late at night, mallet raised, absorbed and careful",
"A warm lit workshop window at night seen from the dark street, blurred sneering townsfolk with beer mugs watching and laughing outside",
"Abel, Cora — A big undertaker and a steady woman and a young stable hand together raise a granite headstone at a hilltop grave, evening gold light",
"Abel — Three people set a granite headstone upright at the head of a grave on a hill at dusk, working together, quiet solemn effort",
"A plain grey granite headstone standing at a grave on a hill at golden dusk, its carved face turned away from view, dignified and simple",
"Abel, Cora — A big undertaker reads aloud hat-off at a hilltop graveside in golden evening light, a woman and a young man beside him, reverent",
"Price — A town boss leans persuading a table of council men in a lamplit room, cold calculation, turning cruelty to advantage",
"Price — A well-fed man slides a contract across a table to council men, a smug deal in progress, lamplight, silver buttons",
"Price — A town boss unrolls a hotel plan over a map of the hill on a table, gesturing grandly, greedy vision, lamplight",
"Abel — A big undertaker stares into an empty coffee tin at a lamplit workbench, worry deep on his face, a mortgaged workshop around him",
"A small fenced grave at the decent edge of a hilltop pauper field in gray light, a quiet resting place under threat, cold morning",
"Abel, Price — A weary undertaker alone in a dim workshop while far off a smug town boss thrives, injustice in the contrast, gray light",
"A fine black lacquered coach drawn by a matched pair rolls up a flat country road toward a frontier town, dust rising, midday",
"A crowd of townsfolk gather on a boardwalk staring as a glossy black coach halts before a fine hotel, curious, midday light",
"Adair — A thin precise elderly man in a black suit and round spectacles steps down from a black coach, calm watchful stillness, midday",
"Adair, Price — A composed lawyer politely declines a well-fed man's offered handshake outside a hotel, cool courtesy, silver buttons dimmed",
"Adair — A spectacled lawyer sets his hat on a saloon bar and addresses the room, dry and commanding, rough men turning to listen, lamplight",
"Adair — A lawyer speaks evenly to a hushed saloon, sharp gray eyes moving across the faces, a leather case under his arm, warm light",
"Adair — Close-up of a dry spectacled lawyer's knowing face, unhurried and certain, warm saloon lamplight, tense listeners blurred behind",
"A hushed saloon of rough frontier men frozen in silence, every face turned toward an unseen speaker, tense, warm lamplight",
"A room of frontier men exchanging sudden greedy calculating glances, the smell of money in the air, warm harsh saloon light",
"Price — A well-fed man springs to his feet in a saloon, thumbs hooked in his silver-buttoned vest, an eager oily smile, seizing the moment",
"Price, Adair — A silver-buttoned town boss beams and gestures grandly at a calm spectacled lawyer in a lamplit saloon, false warmth, watching crowd",
"Price — A town boss spreads his arms in a grand civic gesture in a saloon, oiled smile, claiming credit, self-important, warm light",
"Price — A well-fed man gestures piously toward the window and the hill beyond, laying claim to a charity, smooth lie, lamplight",
"Price — A smug man offers a confiding smile and an open hand to a lawyer, angling for an estate, silver buttons, warm light",
"A saloon of frontier men staring down into their glasses in guilty silence, no one speaking, a purchased hush, warm dim light",
"Adair, Price — A spectacled lawyer studies a smiling town boss with a long dry unreadable stare, quiet menace, warm saloon lamplight",
"Adair — Close-up of a dry lawyer asking a quiet trap of a question, faint knowing coldness, spectacles catching lamplight",
"Price — Close-up of a well-fed man's smile freezing rigid on his face, a flicker of panic behind his eyes, silver buttons, warm light",
"Price — A sweating town boss stands cornered before a watching saloon crowd, forcing his smile, thirty faces on him, tense lamplight",
"Price — A fluent man bluffs smoothly with a raised hand and a fixed smile, improvising a lie, warm saloon light, wary eyes",
"Adair — A lawyer draws a small leather notebook from his coat without looking at it, dry and unhurried, a trap closing, lamplight",
"Adair — A spectacled lawyer holds up a small notebook and speaks precisely, cornering a liar line by line, cold control, warm light",
"Adair — Close-up of a lawyer's hardening face, dry voice gone quiet and sharp, spectacles glinting, relentless, warm lamplight",
"Adair — A lawyer fixes a cold demanding stare across a silent saloon, immovable, the room frozen, warm dim light",
"A young stable hand rises from a saloon chair with burning red ears and clenched fists, nervous but resolved, brave, warm light",
"A young stable hand speaks out passionately in a hushed saloon, fists at his sides, voice breaking with conviction, brave, warm light",
"A young stable hand points and testifies fiercely in a saloon, telling the truth, the crowd riveted, warm harsh light",
"Close-up of a young stable hand's flushed emotional face confessing shame, tears welling, brave and broken, warm lamplight",
"A young stable hand speaks with raw feeling in a saloon, grief and anger mixed, the room silent and ashamed, warm light",
"Price — A well-fed man stands exposed under the stares of a whole saloon, his smile gone, doing frantic sums and coming up short, silver buttons",
"Adair — A lawyer snaps a small leather book shut with grim finality in a saloon, judgment delivered, taking up his hat, warm light",
"Adair — A lawyer holds a bundle of handwritten letters bound in ribbon, calm and certain, a dead man's true record, lamplight",
"Adair — A spectacled lawyer pauses in a saloon doorway putting on his hat, glancing down a dark street, quiet respect, night beyond",
"Adair — A lawyer walks alone down a dark frontier boardwalk at night toward one distant lit window, resolute, cold blue street",
"Abel — A big undertaker winds a brass pocket watch at his lamplit workbench late at night, tender and unaware, sawdust, warm glow",
"Abel — A big undertaker opens his workshop door at night to a visitor, wood shavings on his sleeves, gentle and unsuspecting, lamplight",
"Abel, Adair — A spectacled lawyer steps into a warm sawdust-smelling lamplit workshop as a big undertaker welcomes him gently, coffins in shadow",
"Abel — Close-up of a big undertaker answering simply and honestly by lamplight, plain and unguarded, no idea what is coming, warm light",
"Adair — A lawyer sets a leather document case on a sawdust workbench and unstraps it by lamplight, formal and deliberate, warm glow",
"Adair, Abel — A lawyer speaks a momentous name to a big undertaker in a lamplit workshop, watching his face, the undertaker only bewildered",
"Abel — Close-up of a big undertaker's honestly baffled face hearing a name that means nothing to him, plain and open, warm lamplight",
"Adair — A lawyer reads gravely from a document by lamplight, laying out a vast fortune, dry and steady, a stunned man across the bench",
"Amos — A memory image of a frail old man in a patched coat walking a lonely road, once a silver king, poignant golden dusk",
"Abel — A big undertaker sinks slowly onto a workbench stool, overwhelmed, a lawyer speaking beside him, warm lamplight, coffins in shadow",
"Adair — A spectacled lawyer speaks quietly and sadly by lamplight of a lonely dead man, holding a folded will, warm glow, solemn",
"A folded handwritten will with a broken wax seal held in a lawyer's hands by lamplight, weighty and plain, shallow focus",
"Adair — A lawyer reads the key line of a will aloud by lamplight, dry voice landing hard, a big undertaker listening stunned, warm light",
"Adair — Close-up of a lawyer's steady spectacled face reading a will, quiet gravity, the words landing, warm lamplight",
"Abel — A big undertaker sits with his large hands still on the workbench, shaking his head slowly, refusing, moved and troubled, lamplight",
"Abel — Close-up of a big undertaker working out a hard thought aloud, refusing a fortune on principle, earnest and pained, warm light",
"Adair, Abel — A lawyer regards a big humble undertaker with dawning wonder across a lamplit workbench, a rare admiration, warm glow",
"Adair — A dry spectacled lawyer breaks into a rare warm smile in a lamplit workshop, softened at last, warm glow",
"Abel — A big undertaker's hand moves to his vest pocket and the brass watch, a realization dawning, lamplight, tender",
"Adair — A lawyer reads a dead man's last letter aloud from a page in a thin wild hand, by lamplight, gentle and grave, warm glow",
"Abel — A big undertaker holds the brass pocket watch and thumbs the back case, about to open it, breath held, warm lamplight",
"Abel — Close-up of a big undertaker's shaking careful fingers opening the back of a brass pocket watch by lamplight, tender, intimate",
"Abel — Close-up of a big undertaker gazing down at an open brass pocket watch in his palm, tears rising, overcome, warm lamplight",
"Abel — A big undertaker bows his face into his large hands at his workbench and weeps, sawdust and lamplight, released grief, warm glow",
"Adair, Abel — A lawyer stands quietly by in lamplight letting a weeping undertaker grieve, respectful stillness, warm workshop glow",
"A large crowd of townsfolk gathered before the county clerk's office steps in daylight, hushed and expectant, a public reckoning",
"Adair — A lawyer reads aloud from letters on the clerk's office steps to a bowed silent crowd, truth laid bare, daylight, solemn",
"Price — A well-fed man stands shamed at the edge of a crowd hearing his own cruel words read back, silver buttons dull, undone, daylight",
"Price — A ruined town boss stands isolated and gray-faced as the crowd turns cold shoulders to him, his standing collapsing, harsh daylight",
"A quiet hilltop pauper field left in peace under a wide evening sky, saved, a granite stone standing among the graves, golden light",
"Abel — A big undertaker works calmly at his familiar workbench, unchanged by fortune, quietly content, warm lamplight, coffins in shadow",
"A modest frontier doctor's office with a lit lamp and an open door at dusk, quietly funded kindness, warm welcoming glow",
"A warm plain rest-home room with a lit stove and a row of cots for old travelers, safe and welcoming, gold lamplight, dignity",
"A carved wooden sign over the door of a modest frontier rest home at dusk, warm light, a place of refuge, its lettering unreadable",
"A tidy row of simple headstones in a frontier cemetery at golden dusk, cared for and dignified, long soft light, no legible text",
"A stone-mason chisels a simple verse into a fresh headstone in a sunlit yard, unhurried craft, stone dust in warm light, no legible text",
"Abel, Cora — A big undertaker and a steady auburn-haired woman stand together at a simple frontier church wedding, quiet joy, warm spring light, townsfolk behind",
"Abel — A big undertaker stands at his own wedding surrounded by a subdued grateful town, forgiving and calm, warm daylight, reconciliation",
"Abel — A content older undertaker winds a brass pocket watch by lamplight at home, at peace at last, a woman near him, warm domestic glow",
"A grey granite headstone on the southeast corner of a green hill in long golden evening light, a creek below, peaceful, no legible text",
"Two headstones side by side on a hilltop at golden dusk, one large and plain, one small, resting together, dignified, no legible text",
"A quiet pair of graves on a hill at sunset overlooking a small frontier town and a winding creek, still and reverent, golden light",
"A weathered ghost-town frontier street at dusk, empty and fading, dust blowing through, the memory of a hard place, gray gold light",
"A young stable hand stands tall and quietly proud in a barn doorway in golden light, redeemed by courage, warm and hopeful",
"Amos — A frail old man in a patched coat walks a golden frontier road toward a distant lit town at dusk, his last search, poignant",
"A single warm lamplit doorway glowing gold at the end of a dark frontier street at night, the one open door, welcoming",
"A warm oil lantern glowing against drifting dust at night, steady and inviting, deep gold, the channel's signature image",
"A lit oil lantern beside a frontier window at night, warm gold light spilling into the dark, embers and dust, the final closing image",
]

def run():
    rows = list(csv.DictReader(open("UndertakersKindness-Scenes.csv")))
    assert len(rows) == len(PROMPTS), f"scene/prompt mismatch: {len(rows)} scenes vs {len(PROMPTS)} prompts"
    out = []
    for r, p in zip(rows, PROMPTS):
        sc = int(r["scene"]); a = r["in"]; b = r["out"]; d = float(r["dur_s"])
        out.append(f"SCENE {sc:03d} | {a}-{b} ({d:.1f}s)\n{p}")
    open("UndertakersKindness-ShotList.txt", "w").write("\n\n\n".join(out) + "\n")
    # prompts-only variant (names inline, 2 blank lines, no headers)
    open("UndertakersKindness-Prompts-Only.txt", "w").write("\n\n\n".join(PROMPTS) + "\n")
    durs = [float(r["dur_s"]) for r in rows]
    print(f"{len(rows)} scenes written | {sum(durs)/60:.1f} min | "
          f"{sum(durs):.0f}s (VO 41:31 = 2491s) | shortest {min(durs):.1f}s longest {max(durs):.1f}s")

run()
