# -*- coding: utf-8 -*-
# The Bride They Sent Back (story 7) — VO-synced shot list builder.
# Pairs authored prompts with scene_calculator.py timecodes (narration-only, 35:49).
# One image per scene; duration = narration under it. Text-free, names inline, no em-dashes.
# Ingredients: Hester | Ezra | Dunmore | Arletta. Flashbacks use generic young wording.
import csv

PROMPTS = [
"A dusty frontier main street at midday, a stagecoach just halted, a plain woman climbing down with a carpet bag, a crowd on the boardwalks turning to look",
"Hester — A plain woman with a faint pale scar along her jaw stands alone in a dusty street holding a carpet bag in both hands, dust-gray dress, chin up, unflinching",
"Hester — Close-up of a plain steady woman's face receiving cruel words without flinching, gray eyes wet but level, hard morning light",
"Hester — A woman's face and hand showing a smooth pale healed burn scar along the left jaw and neck and the back of the hand, dignified, plain bonnet, daylight",
"An old faded tintype photograph of a younger unmarked woman held in a weathered hand, a ten-year-old likeness, warm indoor light",
"Dunmore, Hester — A pink well-fed man in a checked waistcoat looks a plain scarred woman over coldly in the street like inspecting damaged goods, dismissive",
"Dunmore — A pink prosperous man in a loud checked waistcoat and thick gold watch chain speaks loudly to the street, self-important, a gesture of complaint",
"Dunmore — A well-fed pink-faced merchant stands puffed up in the street, thumbs near his gold watch chain, pleased with himself, a crowd behind",
"Dunmore, Hester — A rich man gestures disgustedly at a plain scarred woman standing with her bag, publicly rejecting her, townsfolk watching, hard light",
"Hester — A plain scarred woman stands alone and dignified in a dusty street clutching a carpet bag while a crowd watches her be sent away, morning",
"A crowd of frontier townsfolk on boardwalks, some looking away ashamed, one or two smirking, an ugly nervous mockery, flat daylight",
"Hester — A marked plain woman stands rejected and still in the road, bag in both hands, a lonely figure the whole street is staring at, dust",
"Ezra — A very big burned blacksmith with a scar taking the left of his face stands still in the shadow of a smithy doorway, leather apron, watching intently",
"Ezra — Close-up of a scarred blacksmith going utterly still, deep brown eyes fixed across the road in recognition, half disbelief, shadow and light",
"Ezra — A big scarred man in a leather apron takes a slow step out of the smithy shadow into the light, resolved, jaw set, dusty street",
"Hester, Ezra — Across a dusty street, a rejected woman with a bag and a big scarred blacksmith stepping toward her, the moment before everything turns, midday",
"Ezra — A big scarred blacksmith working iron alone at a glowing forge, years of quiet labor, warm firelight on his ruined gentle face",
"A small plain wooden box on a shelf by a bed, a bit of worn ribbon trailing from it, warm lamplight, a kept secret, shallow focus",
"Ezra — A scarred blacksmith holds a small worn brass medal on a ribbon in his big careful hand by lamplight, tender, a private moment",
"An old smithy engulfed in orange flame in the night, sparks and smoke against the dark, a fire ten years past, no people",
"A neighbor drags a young man clear of a burning building at night, the young man's shirt smoking, firelight and alarm, chaos and rescue",
"A gaunt young scarred man catches sight of his burned reflection in a dark window glass and turns his face away, ashamed, cold gray street",
"A gaunt young scarred drifter walks a cold empty road alone, thin and hungry, coat pulled close, bleak gray country, marked and unwelcome",
"A gaunt young burned drifter stands outside a lit bakery window in the cold, drawn by the warm bread light, not daring to go in, dusk",
"A plain quick young woman of twenty with flour on her apron and sleeves shoved up stands in a bakery doorway looking kindly at someone, warm light",
"A young woman looks straight and unafraid toward an unseen scarred face and beckons warmly toward a bakery door, no wince, cold March light",
"A young woman ushers a gaunt young drifter in from the cold through a warm bakery doorway, kind and brisk, golden interior light",
"A young woman sets a full plate before a gaunt scarred young man at a bakery table, warm and matter-of-fact, firelight, bread and coffee",
"A young woman notices a young man favoring a bad burn on his forearm at a table, gentle concern on her face, warm lamplight",
"A young woman gently cleans and dresses a young man's burned forearm at a table with a basin and clean rag, tender unbothered care, warm light",
"A young woman chats easily while tending a scarred young man's arm, both at a bakery table, warm firelight, kindness in the ordinary",
"A young woman presses a small brass medal on a ribbon into a young man's good open palm at a doorway, a parting gift, cold March morning",
"A small worn brass medal on a ribbon lying in a scarred young man's open palm, a treasured gift, soft daylight, shallow focus",
"A gaunt young scarred man climbs onto a departing wagon, looking back once toward a bakery, unspoken words, cold gray morning, dust",
"Ezra — A big scarred blacksmith in his prime works iron at a strong forge, established and skilled, warm firelight, a man who built himself up",
"Ezra — A younger scarred man strikes hot iron as another smith's helper, sweat and sparks, learning the trade, dim forge light",
"A squat strong stone and timber smithy with a good house behind it at the edge of a frontier town, prosperous and solid, warm afternoon light",
"Ezra — A big scarred blacksmith stands alone in his shop doorway watching the town pass, respected but solitary, a marked quiet man, daylight",
"Ezra — A big scarred man sits alone by lamplight in a plain good house, a small wooden box in his hands, solitary, warm low light",
"Ezra — Close-up of a scarred blacksmith holding a worn brass medal by lamplight, remembering, an old ache and hope in his brown eyes",
"Ezra — A scarred man gazes into the dark past a lamp, remembering a face, quiet longing, warm firelight and shadow",
"A stagecoach rolling into a dusty frontier town on a bright morning, a plain woman visible climbing down, the day everything changes",
"Ezra, Dunmore — A big scarred blacksmith strides out of his shop shadow across a dusty street toward a rejection scene, the crowd turning",
"A frontier crowd on boardwalks going suddenly quiet and turning, watching a big scarred man cross the street, hushed, midday",
"Ezra, Hester — A big scarred blacksmith comes to stand beside a rejected plain woman in the street and speaks toward a rich man, steady, crowd watching",
"Ezra — A big scarred blacksmith speaks plainly in a dusty street, hat coming off, grave and unashamed, a hushed crowd, hard light",
"Dunmore, Ezra — A pink merchant stares incredulous at a big scarred blacksmith who has just spoken, the street frozen, midday",
"Ezra, Hester — A big scarred blacksmith holds his hat and looks with careful tenderness at a plain scarred woman, a look no one can read, dusty street",
"Ezra — A big scarred man speaks quietly and firmly in the street, defending a woman's right to choose, dignified, crowd behind, daylight",
"Ezra, Hester — A big scarred blacksmith speaks low and gentle to a wary plain woman in the street, hat in hand, an honest offer, warm side light",
"Hester, Ezra — A plain scarred woman looks up warily at a big gentle scarred man offering her a way out of the sun, considering, dusty street",
"Hester — Close-up of a plain scarred woman studying a stranger's ruined kind face, weighing an impossible choice, gray eyes steady, daylight",
"Hester — A plain woman looks at a big scarred man not quite recognizing him, a faint stir of something forgotten, thoughtful, dusty street",
"Hester — A plain scarred woman's face settling into hard clear resolve, a decision forming, dignified under pressure, daylight",
"Hester, Ezra — A plain scarred woman and a big scarred blacksmith regard each other, two marked people, an understanding passing, warm light in a cold street",
"Hester, Ezra — A plain woman speaks levelly to a big scarred man in the street, guarded dignity, he listening gravely, midday",
"Ezra — Close-up of the scarred side of a blacksmith's face, a ghost of deep feeling passing and gone, controlled, warm light",
"Ezra, Hester — A big scarred blacksmith picks up a woman's carpet bag in his curled scarred hand without hiding it, a quiet gesture, dusty street",
"Hester, Ezra — A plain woman walks away beside a big scarred blacksmith carrying her bag, the crowd parting silent, dust and hard light, dignity restored",
"Hester, Ezra — A plain scarred woman and a big scarred blacksmith stand together before a circuit preacher in a modest front room, a quiet bare wedding, lamplight",
"Hester, Ezra — A newly married scarred couple stand a careful distance apart in a plain room, awkward and quiet, a bargain not yet a love, soft light",
"Hester — A plain scarred woman lies awake on her back in a clean bed in a stranger's house at night, uncertain, moonlight through a window",
"Hester — Close-up of a plain woman's wakeful uncertain face in the dark, wondering, dim blue night light, guarded",
"Ezra — A big scarred blacksmith lies awake on a cot by a cold forge at night, gazing at the dark, a held hope, dim ember light",
"Hester, Ezra — A scarred couple share a quiet careful breakfast at a plain table, formal and gentle, morning light, a beginning",
"Ezra — A big scarred blacksmith lays out terms plainly and awkwardly to his new wife across a kitchen table, grave and kind, morning light",
"Hester, Ezra — A big scarred man gestures to a ledger and a cash box offering his wife the running of it, humble, she listening, warm kitchen light",
"Ezra — Close-up of a big scarred blacksmith speaking earnestly and awkwardly, laying out a kindness as if afraid of thanks, warm light",
"Hester — A plain scarred woman watches her new husband warily across a room, bracing, slowly realizing he is not what she feared, soft light",
"Hester — A plain scarred woman laughs unexpectedly in a warm kitchen, a forge cat at her feet, a first real laugh, sunlight, joy breaking through",
"Ezra — A big scarred blacksmith stands alone in his shop with a hand flat on the cold anvil, overcome by a small joy, head bowed, dim light",
"Hester — A plain woman works neat columns in a clean ledger at a kitchen table by lamplight, sharp and capable, warm glow",
"Hester — A plain scarred woman stands straight-backed behind a counter looking a man level in the eye over an open ledger, quietly formidable, daylight",
"Hester — A plain scarred woman in a plain dress carries a ledger down a frontier street between shops, respected now, warm afternoon light",
"Hester, Ezra — A scarred couple ease into comfort together in a warm kitchen, a little closer now, gentle, lamplight, a marriage growing",
"Hester, Ezra — A plain woman cleans and dresses her big scarred husband's cut hand at a kitchen table, tender care, warm lamplight, an echo of the past",
"Ezra — Close-up of a big scarred blacksmith sitting very still under his wife's tending hands, ten years going through him, overcome quietly, warm light",
"Ezra — A scarred blacksmith holds his own hand where his wife tended it, a heavy secret in his face, firelight, unspoken",
"Dunmore — A pink well-fed man watches from a fine window with a curdled resentful face, galled, cold parlor light, a rich man's spite",
"Arletta — A cold pretty young woman in an expensive dress and too much jewelry sits discontented in a fine parlor, bored and grasping, chilly light",
"Dunmore, Arletta — A pink merchant and a cold pretty wife sit apart and loveless in a fine parlor, a frozen marriage, expensive and joyless, cold light",
"Dunmore — A pink resentful man glares out his fine window at a distant happy scarred couple walking, jealousy hardening his face, cold parlor",
"Dunmore — A well-fed man broods over papers at a fine desk, plotting, cold calculation replacing his smile, lamplit study",
"A land note and mortgage papers on a dark desk, a signature and a bank stamp, cold legal machinery, lamplight, shallow focus",
"Dunmore — A pink merchant signs a demand paper at his desk with a thin cruel smile, calling a note, spiteful, lamplit",
"Dunmore — A well-fed man hands a folded demand note to a clerk with a smug smile, cold business, a fine mercantile interior",
"Ezra — A big scarred blacksmith stands in his shop reading a folded legal paper slowly, the ground going out from under him, grim, daylight",
"Ezra, Hester — A big scarred man sets a demand paper on the kitchen table and speaks heavily to his wife, defeated and sorry, warm lamplight",
"Hester, Ezra — A plain woman picks up a legal paper from the table and reads it fast while her husband watches, calm gathering, lamplight",
"Hester — Close-up of a plain scarred woman reading a legal paper twice, sharp focused eyes, no fear, a plan forming, warm lamplight",
"Hester — A plain woman looks up from a paper with a sudden still intensity, having seen something, sharp and alert, lamplight",
"Hester, Ezra — A plain woman questions her big scarred husband intently across a table, a plan turning in her mind, lamplight",
"Hester — A plain scarred woman speaks with quiet authority across a kitchen table, a town's books in her head, formidable, lamplight",
"Hester — Close-up of a plain woman's face lit with cold clear certainty, a hunter who has found the trail, lamplight",
"Hester — A plain scarred woman stands up straight-backed at the table, a formidable strength rising in her, the fighter revealed, lamplight",
"Hester — A plain woman gathering papers and giving crisp instructions at a lamplit table, marshaling a war of ledgers, resolute, warm light",
"Hester — Close-up of a plain scarred woman with the faintest fierce smile, an open ledger before her, dangerous and certain, warm lamplight",
"Dunmore — A pink man's smug face, unaware he has reached for the one weapon his victim can hold, overconfident, cold light",
"Hester — A plain woman's scarred hand flat on an open ledger by lamplight, quiet power, the trap she will spring, shallow focus",
"Dunmore, Hester — A rich man turns away dismissive while a plain scarred woman watches him steadily, the misjudgment that will ruin him, daylight",
"Hester — A plain scarred woman opens a great ledger at a lamplit table late at night, beginning the reckoning, absorbed, warm glow",
"Hester — A plain woman surrounded by spread papers and open ledgers at a lamplit kitchen table deep in the night, working, focused, warm light",
"Hester — Townsfolk quietly laying their own crushing notes before a plain scarred woman at her table, a gathering war, lamplight, solemn",
"Hester — Close-up of a plain woman's finger stopping on a line in a ledger, a discovery, sharp triumph in her eyes, lamplight",
"Hester — A plain woman marks a figure in a ledger with a pen, proof found, cold satisfaction, lamplit night",
"Hester — A plain scarred woman lays papers side by side comparing them by lamplight, tracing a decade of theft, meticulous, warm glow",
"Hester — A plain woman writing steadily in a clean ledger by lamplight, a record of a rich man's crimes, resolute, warm light",
"Hester — A plain scarred woman hands a bound sheaf of papers across a desk to an official at the county seat, formal and sure, daylight",
"Hester — A plain woman shows an open ledger to a small group of relieved townsfolk, revealing their debts are void, hope on their faces, warm light",
"Hester — A plain scarred woman dresses in her good gray traveling dress before a small mirror, squaring herself for a reckoning, resolute, soft light",
"Hester — A plain scarred woman walks down a sunlit frontier main street with a ledger under her arm, chin up, townsfolk gathering on boardwalks",
"Hester, Dunmore — A plain woman enters a fine mercantile and faces a pink merchant behind his counter, ledger in hand, the crowd at the door, tense",
"Hester — A plain scarred woman speaks quiet and level across a counter to a rich man, unanswerable calm, an open ledger between them, warm light",
"Hester, Dunmore — A plain woman turns a ledger page facing a stiffening merchant, calmly laying out his crime, the crowd watching, tense light",
"Hester — Close-up of a plain scarred woman's steady face delivering the truth, quiet devastating control, an open ledger, warm mercantile light",
"Hester, Dunmore — A plain woman lays a final damning sheet on a counter before a graying merchant, the trap sprung, the crowd leaning in",
"Dunmore — A pink merchant's face going gray and stricken as he stares down at papers on his counter, cornered and ruined, warm light",
"Hester, Dunmore — A plain scarred woman closes a ledger with quiet finality before a stricken rich man, an ultimatum given, the crowd hard-eyed",
"A street full of hard-eyed frontier townsfolk on boardwalks watching a mercantile doorway, waiting, tense daylight, a reckoning at hand",
"Dunmore — Close-up of a defeated pink merchant realizing he cannot buy his way out, understanding dawning gray on his face, warm light",
"Dunmore — A ruined merchant stands in his own doorway before the town forgiving debts aloud, gray-faced and humbled, hard daylight, the crowd watching",
"Dunmore, Ezra — A pink merchant tears a demand note in half with soft hands while a big scarred blacksmith watches from the crowd, unreadable, daylight",
"Hester — A plain scarred woman walks back through a frontier town as men quietly tip their hats to her, respect earned, warm afternoon light",
"Hester, Ezra — A plain woman and her big scarred husband walk home together through town, heads bent close, a hard-won peace, warm gold light",
"Hester — A plain scarred woman alone in her warm kitchen, a shadow of private doubt under her happiness, gentle firelight, unresolved",
"Hester — A plain woman dusting a shelf by the bed knocks a small wooden box which falls open, a moment of accident, warm domestic light",
"A small worn brass medal on a soft ribbon lying on wooden floorboards, warm lamplight catching it, a fallen secret, shallow focus",
"Hester — Close-up of a plain scarred woman kneeling, a worn brass medal in her open hand, stunned recognition breaking over her face, warm light",
"A memory flash of a young woman pressing a brass medal into a gaunt young scarred man's palm at a bakery door, tender, cold March light",
"Hester — A plain woman kneeling on the floor, memory and realization colliding in her face, the past ten years rearranging, warm lamplight",
"Hester, Ezra — A plain woman kneels on the floor with a medal in her hand as a big scarred man stops in the doorway behind her, the truth in the room",
"Hester, Ezra — A plain scarred woman looks up from the floor at her big scarred husband in the doorway, a wordless recognition passing between them, warm light",
"Ezra — A big scarred blacksmith stands in a doorway, his composure breaking, speaking a ten-year truth, tender and undone, warm lamplight",
"Ezra — Close-up of a big scarred man's face, ruined and gentle, struggling to speak long-held words, tears near, warm light",
"Ezra — A big scarred blacksmith with lowered eyes confessing he had given up the search, quiet grief, warm doorway light",
"Ezra, Hester — A big scarred man looking at his scarred wife with overwhelmed recognition, the moment he knew her relived, warm light",
"Ezra — Close-up of a big scarred blacksmith speaking from the heart, ten years of love in his ruined face, undone, warm lamplight",
"Ezra, Hester — A big scarred man pours out his heart to his kneeling wife, both marked faces close, a decade of feeling, warm firelight",
"Ezra — A huge scarred blacksmith breaking down in his own doorway, weeping, a man undone by long wanted love, warm lamplight",
"Hester, Ezra — A plain scarred woman on the floor and a big scarred man both overcome, the whole truth finally spoken, warm gold light",
"Hester — A plain scarred woman on the floor, the strength she carried finally giving way, tears coming at last, warm firelight",
"Hester, Ezra — A big scarred man crosses a room and kneels down beside his weeping wife on the floor, careful and enormous, warm lamplight",
"Hester, Ezra — A big scarred blacksmith wraps his arms around his scarred wife on the floor, both holding on, no words needed, warm gold firelight",
"Dunmore — A diminished pink man loads a trunk onto a coach outside a sold mercantile, leaving town smaller and poorer, gray morning, no one watching",
"Dunmore — A lone well-fed man rides away in a coach down a country road, diminished, the town behind him, cold gray light",
"Dunmore — A pink man's hollow face at a coach window looking back once, having learned nothing, poorer than he knows, gray light",
"Hester, Ezra — A scarred couple stand together in the doorway of their smithy and good house, keeping their life, warm settled afternoon light",
"Ezra, Hester — A big scarred blacksmith at his forge and his plain wife at her ledger, the two the town relies on, warm industrious light",
"Hester — A plain scarred woman listens kindly to a troubled townsperson across her counter, trusted with figures and griefs both, warm light",
"Hester, Ezra — A scarred couple share a warm supper table with a cast-off marked stranger they have taken in, found family, golden lamplight",
"Ezra — A big scarred blacksmith gives a scarred young drifter a place at the forge and a trade, passing on a kindness, warm shop light",
"A warm crowded supper table of the world's misfits in a homely house at night, the warmest house in town, golden light, belonging",
"Hester, Ezra — An older scarred couple by the hearth hold a worn brass medal together, remembering, at peace, warm firelight",
"A soft memory image of a young woman in a bakery doorway beckoning a scarred stranger in from the cold, the kindness that started it all, warm glow",
"Hester, Ezra — An older scarred couple stand close in the doorway of their smithy at golden dusk, a life built from two scars, warm light",
"A warm lit smithy and home at the end of a frontier street at dusk, gold light in the windows, the truest home in town, inviting",
"Hester — Close-up of a plain scarred woman's serene content face by firelight, worth more than any glance ever gave her, warm gold",
"A worn brass medal resting in two clasped weathered hands by firelight, love that outlasted ten years, warm gold, shallow focus",
"A warm lit window and open door of a frontier home at night, a table set and welcoming within, gold light spilling into the dark, the closing image",
]

# Period anchor stamped on EVERY prompt so each line renders old-west even when
# pasted individually (no file header to rely on). Fixes modern-setting renders.
ANCHOR = ", 1880s American Old West frontier, period-accurate frontier clothing and props, no modern objects, no contemporary clothing"

def run():
    rows = list(csv.DictReader(open("BrideTheySentBack-Scenes.csv")))
    assert len(rows) == len(PROMPTS), f"{len(rows)} scenes vs {len(PROMPTS)} prompts"
    stamped = [p + ANCHOR for p in PROMPTS]
    out = []
    for r, p in zip(rows, stamped):
        out.append(f"SCENE {int(r['scene']):03d} | {r['in']}-{r['out']} ({float(r['dur_s']):.1f}s)\n{p}")
    open("BrideTheySentBack-ShotList.txt", "w").write("\n\n\n".join(out) + "\n")
    open("BrideTheySentBack-Prompts-Only.txt", "w").write("\n\n\n".join(stamped) + "\n")
    durs = [float(r["dur_s"]) for r in rows]
    print(f"{len(rows)} scenes | {sum(durs)/60:.1f} min | {sum(durs):.0f}s (VO 35:49 = 2149s) | "
          f"shortest {min(durs):.1f}s longest {max(durs):.1f}s")

run()
